# Generated by Django 5.0.1 on 2024-04-23 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Newsname', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Itemname', models.CharField(max_length=200)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('newsitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.newletter')),
            ],
        ),
    ]
